name: CI

on: [push, pull_request]

env:
  UV_VERSION: "0.7.19"

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Uv with Python and Nox
        uses: ./.github/actions/setup-uv-nox
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Test with Nox
        run: uv run nox -s test-${{ matrix.python-version }}

  quality:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        nox-session: ["lint", "type_check"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Uv with Python and Nox
        uses: ./.github/actions/setup-uv-nox
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install dependencies
        run: uv sync --locked

      - name: Test with Nox
        run: uv run nox -s ${{ matrix.nox-session }}
