name: python

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
        include:
          # Limit Windows testing to one Python version.
          - os: windows-latest
            python-version: "3.9"
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-poetry-nox
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Test with Nox
        run: poetry run nox -s "test-${{ matrix.python-version }}"

  quality:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        job:
          - { nox-session: lint, poetry-groups: "lint" }
          # `type_check` needs `main` and `test` dependencies for inline type
          # annotations.
          - { nox-session: type_check, poetry-groups: "type_check,main,test" }
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-poetry-nox

      - name: Install Nox group dependencies
        run: poetry install --only "${{ matrix.job.poetry-groups }}"

      - name: Test with Nox
        run: poetry run nox -s "${{ matrix.job.nox-session }}"

  poetry-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-poetry-nox

      - name: Validate Poetry Configuration and Lockfile Freshness
        run: poetry check --lock
